main: com.thisisnzed.nprotect.launcher.Launcher
name: nProtect
version: 1.0.0
author: Najtt
commands:
  protect:
    aliases: [security, nprotect, protection]
    description: Main command of nProtect
  pin:
    description: Secure accounts with pin
  mapscanner:
    description: Scan the map